### ISSUE TITLE
Fix shake128/256 tests

### ISSUE THREAD

**Issue by SeanTAllen** [ponylang/crypto#31]
As part of the PR that added, the non-digest tests were added as digest tests.

https://github.com/ponylang/crypto/pull/28

Additionally the digest tests differ from the existing digest tests and should be updated accordingly.

Please see how the other tests work. Shake tests should be updated accordingly.

@damon-kwok can you handle this?

**Comment by SeanTAllen** [comment]
It appears that Shake128/256 are both missing from `hash_fn.pony` when those are added the test cases should be made to look like the others.

**Comment by mfelsche** [comment]
There is no C function we could use for creating a Shake128/256 `HashFn`. We would need to use the `Digest.shake128` / `Digest.shake256` for implementing those.

**Comment by damon-kwok** [comment]
@SeanTAllen  Yes, I will focus on this project recently.

**Comment by SeanTAllen** [comment]
@mfelsche did you test that locally? 

Either way, given that we have no tests that run in CI for this currently, any PR for this shouldn't be merged until https://github.com/ponylang/crypto/issues/29 is done so that we can be sure that the tests are working and passing.

**Comment by mfelsche** [comment]
I did not, i assumed ci was testing the openssl 1.1.1

**Comment by SeanTAllen** [comment]
@mfelsche it is not, it is using libressl and testing as seen here:

https://github.com/ponylang/crypto/blob/master/.github/workflows/pr.yml#L24

**Comment by SeanTAllen** [comment]
@mfelsche how did you determine that there are C functions that we could use for creating a Shake128/256 HashFn? Did you check the source? I'd like to know for the future if others come in the best way to determine that. I find the openssl source hard to navigate so pointers would be appreciated.

**Comment by mfelsche** [comment]
I was searching the index of man pages: https://www.openssl.org/docs/man1.1.1/man3/

**Comment by SeanTAllen** [comment]
Closed by #40
