### ISSUE TITLE
Add digest name support

### ISSUE THREAD

**Issue by damon-kwok** [ponylang/crypto#35]
- Get digest type
```pony
class Digest
  let _name: String = "unknow"
  new md4() => 
    _name = "md4"
   ...
  fun name(): String => _name
```
- Create digest by name
```pony
class Digest
  let _name: String
  new create(name': String) =>
    _name = name'
    match name'
    | "md4" =>...
    ...
    end
```

**Comment by SeanTAllen** [comment]
I don't think selecting a Digest based on a string is a good idea. There can be runtime rather than compile time errors. I'm not in favor of the "create digest by name" idea.

**Comment by damon-kwok** [comment]
Yes, I try to test my ideas before deciding whether to do it.
